In [1]:
import pandas as pd 
import numpy as np 


In [2]:
df = pd. read_csv("dataset/diabetes.csv")
df

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0              6      148             72             35        0  33.6   
1              1       85             66             29        0  26.6   
2              8      183             64              0        0  23.3   
3              1       89             66             23       94  28.1   
4              0      137             40             35      168  43.1   
..           ...      ...            ...            ...      ...   ...   
763           10      101             76             48      180  32.9   
764            2      122             70             27        0  36.8   
765            5      121             72             23      112  26.2   
766            1      126             60              0        0  30.1   
767            1       93             70             31        0  30.4   

     DiabetesPedigreeFunction  Age  Outcome  
0                       0.627   50        1  
1                       0.351   31        0  
2                       0.672   32        1  
3                       0.167   21        0  
4                       2.288   33        1  
..                        ...  ...      ...  
763                     0.171   63        0  
764                     0.340   27        0  
765                     0.245   30        0  
766                     0.349   47        1  
767                     0.315   23        0  

[768 rows x 9 columns]

In [3]:
df.corr()["Outcome"]

Pregnancies                 0.221898
Glucose                     0.466581
BloodPressure               0.065068
SkinThickness               0.074752
Insulin                     0.130548
BMI                         0.292695
DiabetesPedigreeFunction    0.173844
Age                         0.238356
Outcome                     1.000000
Name: Outcome, dtype: float64

In [4]:
df.drop(columns=["SkinThickness","BloodPressure"],inplace=True)

In [5]:
df

Pregnancies  Glucose  Insulin   BMI  DiabetesPedigreeFunction  Age  \
0              6      148        0  33.6                     0.627   50   
1              1       85        0  26.6                     0.351   31   
2              8      183        0  23.3                     0.672   32   
3              1       89       94  28.1                     0.167   21   
4              0      137      168  43.1                     2.288   33   
..           ...      ...      ...   ...                       ...  ...   
763           10      101      180  32.9                     0.171   63   
764            2      122        0  36.8                     0.340   27   
765            5      121      112  26.2                     0.245   30   
766            1      126        0  30.1                     0.349   47   
767            1       93        0  30.4                     0.315   23   

     Outcome  
0          1  
1          0  
2          1  
3          0  
4          1  
..       ...  
763        0  
764        0  
765        0  
766        1  
767        0  

[768 rows x 7 columns]

In [6]:
X = df.iloc[:,:-1].values
X

array([[  6.   , 148.   ,   0.   ,  33.6  ,   0.627,  50.   ],
       [  1.   ,  85.   ,   0.   ,  26.6  ,   0.351,  31.   ],
       [  8.   , 183.   ,   0.   ,  23.3  ,   0.672,  32.   ],
       ...,
       [  5.   , 121.   , 112.   ,  26.2  ,   0.245,  30.   ],
       [  1.   , 126.   ,   0.   ,  30.1  ,   0.349,  47.   ],
       [  1.   ,  93.   ,   0.   ,  30.4  ,   0.315,  23.   ]])

In [7]:
y =  df.iloc[:,-1].values

In [8]:
y

array([1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0,
       1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1,
       0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0,
       1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 1, 1,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0,
       1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1,
       0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1,
       1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1,
       1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0,
       1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0,
       1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0,
       0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1,

In [9]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=42)

In [10]:
from sklearn.preprocessing import StandardScaler

In [11]:
scale_train = StandardScaler()

In [12]:
X_train= scale_train.fit_transform(X_train)

In [13]:
X_train

array([[-0.52639686, -1.15139792, -0.70120553, -4.13525578, -0.49073479,
        -1.03594038],
       [ 1.58804586, -0.27664283, -0.70120553, -0.48916881,  2.41502991,
         1.48710085],
       [-0.82846011,  0.56687102,  0.01344832, -0.42452187,  0.54916055,
        -0.94893896],
       ...,
       [ 1.8901091 , -0.62029661, -0.70120553,  1.76054443,  1.981245  ,
         0.44308379],
       [-1.13052335,  0.62935353, -0.70120553,  1.34680407, -0.78487662,
        -0.33992901],
       [-1.13052335,  0.12949347, -0.70120553, -1.22614383, -0.61552223,
        -1.03594038]])

In [14]:
X_test = scale_train.transform(X_test)

In [15]:
import tensorflow
from tensorflow import keras
from keras import Sequential
from keras.layers import Dense

In [16]:
# #tuning optimizers 
# def build_model(hp):
#     model = Sequential()
#     model.add(Dense(32,input_dim = 6, activation="relu"))
#     model.add(Dense(1,activation="sigmoid"))
#     optimizer = hp.Choice("optimizers",values = ["adam","rmsprop","sgd","adadelta"])
#     model.compile(optimizer=optimizer,loss = "binary_crossentropy",metrics = ["accuracy"])
#     return model

In [17]:
import kerastuner as kt

C:\Users\PMLS\AppData\Local\Temp\ipykernel_7428\1654478174.py:1: DeprecationWarning: `import kerastuner` is deprecated, please use `import keras_tuner`.
  import kerastuner as kt


In [18]:
# tuner  = kt.RandomSearch(build_model,objective="val_accuracy",max_trials=5,directory ="mydir",project_name = "tuning")

In [19]:
# tuner.search(X_train,y_train,epochs =5,batch_size = 32,validation_data= (X_test,y_test))

In [20]:
# hp = tuner.get_best_hyperparameters()[0].values
# hp

In [21]:
# model = tuner.get_best_models(num_models=1)[0]
# model

In [22]:
# model.summary()

In [23]:
# model.fit(X_train,y_train,batch_size=32,epochs =100 ,initial_epoch=6,validation_data=(X_test,y_test))

In [24]:
def build_model(hp):
    model = Sequential()
    units = hp.Int("units",min_value=32,max_value=128,step=2)
    model.add(Dense(units=units,input_dim=6,activation="relu"))
    model.add(Dense(1,activation = "sigmoid"))
    model.compile(optimizer="rmsprop",loss = "binary_crossentropy",metrics = ["accuracy"])
    return model

In [25]:
tuner=kt.RandomSearch(build_model,objective="val_accuracy",max_trials=5,directory = "mydir",project_name = "tuning")

C:\Users\PMLS\AppData\Roaming\Python\Python312\site-packages\keras\src\layers\core\dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


In [26]:
tuner.search(X_train,y_train,epochs =5,validation_data = (X_test,y_test))

Trial 5 Complete [00h 00m 06s]
val_accuracy: 0.7532467246055603

Best val_accuracy So Far: 0.798701286315918
Total elapsed time: 00h 00m 33s
